apiVersion: v1
kind: Service
metadata:
  name: openfreemap
  namespace: openfreemap
  labels:
    app: openfreemap
    component: nginx
spec:
  type: LoadBalancer  # Change to ClusterIP if using Ingress
  selector:
    app: openfreemap
    component: nginx
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  
  # Session affinity for better caching
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600

